<?php

namespace JT\NotificationBundle\Repository;

use JT\NotificationBundle\Model\NotifyableInterface;
use Doctrine\ORM\Query\Expr\Join;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNotificationsOfUser(NotifyableInterface $user, $limit = 5)
    {
        return $this->createQueryBuilder('n')
            ->select('n, un.opened, un.openedAt')
            ->join("JTNotificationBundle:UserNotification", 'un', Join::WITH, 'n = un.notification')
            ->where('un.user = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult()
        ;
    }
}
